### ISSUE TITLE
Cannot build in latest Xcode 13

### ISSUE THREAD

**Issue by advatar** [outfoxx/PotentCodables#12]
It seems like the BidirectionalCollection and Collection protocols has changed.

/Users/johansellstrom/PotentCodables/Sources/PotentASN1/AnyString.swift:62:1: error: type 'AnyString' does not conform to protocol 'BidirectionalCollection'
extension AnyString: StringProtocol {
^
/Users/johansellstrom/PotentCodables/Sources/PotentASN1/AnyString.swift:62:1: error: unavailable subscript 'subscript(_:)' was used to satisfy a requirement of protocol 'BidirectionalCollection'
extension AnyString: StringProtocol {
^
Swift.Collection:3:12: note: 'subscript(_:)' declared here
    public subscript(bounds: Range<Self.Index>) -> Self.SubSequence { get }
           ^
Swift.BidirectionalCollection:14:14: note: requirement 'subscript(_:)' declared here
    override subscript(bounds: Range<Self.Index>) -> Self.SubSequence { get }
             ^
/Users/johansellstrom/PotentCodables/Sources/PotentASN1/AnyString.swift:62:1: error: type 'AnyString' does not conform to protocol 'Collection'
extension AnyString: StringProtocol {
^
/Users/johansellstrom/PotentCodables/Sources/PotentASN1/AnyString.swift:62:1: error: unavailable subscript 'subscript(_:)' was used to satisfy a requirement of protocol 'Collection'
extension AnyString: StringProtocol {
^
Swift.Collection:3:12: note: 'subscript(_:)' declared here
    public subscript(bounds: Range<Self.Index>) -> Self.SubSequence { get }
           ^
Swift.Collection:12:5: note: requirement 'subscript(_:)' declared here
    subscript(bounds: Range<Self.Index>) -> Self.SubSequence { get }
    ^

**Comment by kdubb** [comment]
Fixed in 1.8.2
