### ISSUE TITLE
cocoapods support or Source integration

### ISSUE THREAD

**Issue by www036** [outfoxx/PotentCodables#21]
This is a great library, can you add it to cocoapods to make easier for ppl to import? Or to source integration? Thanks!

**Comment by kdubb** [comment]
I'm open to this and I looked into it but there are a few problems I'm not sure how to solve (or if they are solvable).

1. Some dependencies don't support CocoaPods; the most important of which is `apple/swift-collections`.
1. The separate targets need to be in SubSpecs that each become a Swift module. I assume this is how SubSpecs work but I'm not sure.
1. Cfyaml is a C target in the Swift package. How is that translated to a Pod SubSpec?

**Comment by kdubb** [comment]
Closing due to the prevalence of SPM at this point. If there is somebody who has the knowledge (given the above) and is willing make a PR, I am always open to adding the support
