### ISSUE TITLE
Trouble with Encoding of Versioning

### ISSUE THREAD

**Issue by nicolaischneider** [outfoxx/PotentCodables#5]
Hi,

I'm having some issues with the versioning scheme. How can I encode the following structure in asn1: `Version ::= INTEGER { v1(1) }`, in other words, how should structure and scheme look like?

Thanks for your help in advance,
Nico

**Comment by kdubb** [comment]
Here's how `TBSCertficate`'s schema is specified, which starts with a version: 

https://github.com/outfoxx/Shield/blob/a885653d1555624080e6f0e66e2229825d386f23/Sources/ShieldX509/TBSCertificate.swift#L103
