### ISSUE TITLE
AnyValue dictionary encoding as an Array

### ISSUE THREAD

**Issue by GP89** [outfoxx/PotentCodables#53]
Hey!

I'm seeing a weird bug where a dictionary is getting encoded as an array? This didn't used to happen in older version (I tried on v1.8.2)

Example code to reproduce the issue:
```
import Foundation
import PotentCodables


func main() {
	
	var myDict = [String: [String: AnyValue]]()
	
	myDict["key"] = ["innerVal": AnyValue.bool(true)]
	myDict["key2"] = ["innerDict": AnyValue.dictionary([
		"innerKey": true
	])]
							 
	let encoder = JSONEncoder()
	encoder.outputFormatting = .prettyPrinted
	
	if let data = try? encoder.encode(myDict), let json = String.init(data: data, encoding: .utf8) {
		print(json)
	}
	
}

main()
```

Output on current main:
```
{
  "key" : {
    "innerVal" : true
  },
  "key2" : {
    "innerDict" : [
      "innerKey",
      true
    ]
  }
}
```

Output on 1.8.2:
```
{
  "key" : {
    "innerVal" : true
  },
  "key2" : {
    "innerDict" : {
      "innerKey" : true
    }
  }
}

**Comment by kdubb** [comment]
This likely due to the switch to ordered dictionaries to maintain serialization order. I'll look into it.

**Comment by kdubb** [comment]
Ahhh. You need to use the `JSONEncoder` from PotentCodables/PotentJSON. An easy way to reference it is to use `JSON.Encoder`.

Foundation's `JSONEncoder` uses the standard encoder for `OrderedDictionary` which is to use an array of arrays to ensure ordering.

**Comment by kdubb** [comment]
Yes it is a drop-in replacement with added support for all the advanced features PC provides.
