### ISSUE TITLE
'Float16' is unavailable in Mac Catalyst

### ISSUE THREAD

**Issue by jorgenisaksson** [outfoxx/PotentCodables#66]
We get this error when building for Mac Catalyst. "'Float16' is unavailable in Mac Catalyst" Any ideas on how to fix that?

**Comment by kdubb** [comment]
@jorgenisaksson This should be fixed in `3.4.0`

**Comment by jorgenisaksson** [comment]
I can confirm that it works with 3.4.0. Thx!
